additional:
  # temporarily include repos manually # https://github.com/github/docs/issues/3630
  - "node-*"
  - "!node-create"
  - "!node-debug"
  - "!node-error"
  - "!node-fs-writefile-promise"
  - "!node-har"
  - "!node-har-validator"
  - "!node-install-group"
  - "!node-marked-promise"
  - "!node-spawn-promise"
  - "!node-updated"

files:
  - "!**.js"
  - "!README.md"
  - "!docs/README.md"
  - "!colophon.yml"
  - "!package*.json"
  - "!.github/matrix.json"
  - "!**/template-sync.yml"
