additional:
  # temporarily include repos manually # https://github.com/github/docs/issues/3630
  - "node-*"
  - "!node-fs-writefile-promise"
  - "!node-har"
  - "!node-har-validator"

files:
  - "!**.js"
  - "!README.md"
  - "!docs/README.md"
  - "!colophon.yml"
  - "!package*.json"
  - "!.github/matrix-*.json"
  - "!**/template-sync.yml"
  - "!.github/dependabot.yml"
  - "!.github/workflows/*.yml"
  - .github/template/push.yml: .github/workflows/push.yml
  - .github/template/pull_request_target.yml: .github/workflows/pull_request_target.yml
  - .github/template/dependabot.yml: .github/dependabot.yml
